site_name: TUTORIAL
site_author: Víctor J. Fernández
site_url: https://tutorialpythonbioquimica.com/
repo_name: victorffdez/GitHub
repo_url: https://github.com/Victorffdez/Python_Biochemistry_Tutorial
edit_uri: ""

nav:
    - Inicio: index.md
    - Introducción a Python: 2_Introduccion_python.md
    - PyCharm: 3_Pycharm.md
    - Variables, objetos atómicos y operadores: 4_Variables.md
    - Estructuras de datos: 5_EstructurasDatos.md
    - Estructuras de control: 6_EstructurasControl.md
    - Funciones: 7_Funciones.md
    - Importación y exportación de datos: 8_Importacion_Datos.md
    - Cadenas de caracteres: 9_Cadenas_Caracter.md
    - Graficación: 10_Graficas.md
    - Manipulación de data frames: 11_DataFrames.md
    - Acerca de: AcercaDe.md

theme:
    name: material
    logo: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1200px-Python-logo-notext.svg.png
    favicon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1200px-Python-logo-notext.svg.png
    icon:
      repo: fontawesome/brands/github
    palette:
        - scheme: default
          toggle:
                icon: material/toggle-switch
                name: Switch to dark mode
        - scheme: slate
          primary: red
          accent: indigo
          toggle:
                icon: material/toggle-switch-off-outline
                name: Switch to light mode
    language: es
    features:
      - navigation.instant
      - navigation.top
      - search.suggest
      - search.highlight
      - search.share
      -
plugins:
  - search:
      lang:
        - es
        - en
extra:
  search:
    language: es, en
  social:
    - icon: material/twitter
      link: https://twitter.com/Fac_CienciasUCO?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
    - icon: material/school
      link: https://uco.es/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/school/facultadcienciasuco/?originalSubdomain=es
    - icon: fontawesome/brands/python
      link: https://es.python.org/
  generator: false #Elimina spam de mkdocs al final del documento

copyright: Copyright © 2021-2022 Víctor J. Fernández. Todos los derechos reservados.
markdown_extensions:  #Extensión necesaria para redimensionar imagenes fácilmente.
  - attr_list
  - md_in_html
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg















